name: zerofoodwaste
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.2
  flutter_image_compress: ^2.1.0
  google_maps_flutter: ^2.6.0
  geolocator: ^11.0.0
  geocoding: ^2.1.0
  http: ^1.1.0
  socket_io_client: ^2.0.0
  flutter_secure_storage: ^9.2.4
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  provider: ^6.1.2
  json_annotation: ^4.9.0
  shared_preferences: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - images/